### ISSUE TITLE
Connection Type

### ISSUE THREAD

**Issue by AndrewSChapman** [eBookingServices/mysql-lited#4]
Hi there, this isn't a bug but just wondering if you can advise what Type I can use to store the MySQL connection as a private class attribute.

e.g.

class DB {
    private Connection conn;

   this {
       this.conn = client.lockConnection();
   }
}

Can you provide an example of what to use for "Connection" as the type?

Cheers and thanks!

**Comment by marcioapm** [comment]
I just pushed and tagged a new version that will allow you to do this easierly:

``` d
class DB {
  private MySQLClient.LockedConnection conn;
  this {
    this.conn = client.lockConnection();
  }
}
```

Although, I would advise you not to store connections. Connection should be locked for as little amount of time as possible, so that they get back to the connection pool and get reused as much as possible.

Myself, I have a global MySQLClient object per thread, which hands out connections as needed.
Each function that needs a connection just creates a new one like so:

``` d
private static MySQLClient client_ = null;

auto connection(string dbName = null) {
  if (client_ is null) // not initialized in this thread yet
    client_ = new MySQLClient("connectionsettings...");
  assert(client_ !is null);

  auto conn = client_.lockConnection();
  assert(conn);

  if (dbName.length)
    conn.use(dbName);

  return conn;
}

// then in my user code I have
auto conn = connection();
conn.execute("select id from users");
```

**Comment by AndrewSChapman** [comment]
Thank you for this - works like a charm!
